"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const stages=["novo","negociacao","contratado","producao","aguardando","entregue","manutencao"];
export default function Page(){
const [user,setUser]=useState<any>(null),[member,setMember]=useState(false),[clients,setClients]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[tx,setTx]=useState<any[]>([]),[tab,setTab]=useState("Kanban"),[form,setForm]=useState<any>({}),[msg,setMsg]=useState("");
async function load(){const [m,c,p,t]=await Promise.all(["members","clients","projects","transactions"].map(x=>db.from(x).select("*")));setMember(!!m.data?.length);setClients(c.data||[]);setProjects(p.data||[]);setTx(t.data||[])}
useEffect(()=>{db.auth.getUser().then(({data})=>setUser(data.user));const {data}=db.auth.onAuthStateChange((_,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(user)load()},[user]);
async function add(table:string,payload:any){const {error}=await db.from(table).insert(payload);setMsg(error?.message||"Salvo");if(!error){setForm({});load()}}
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const income=tx.filter(x=>x.kind==="receita"&&x.paid_at).reduce((s,x)=>s+Number(x.amount),0);
const costs=tx.filter(x=>x.kind==="despesa"&&x.paid_at).reduce((s,x)=>s+Number(x.amount),0);
if(!user)return <div className="card" style={{maxWidth:440,margin:"12vh auto"}}><h1>✦ Agency Hub</h1><p>Login dos sócios</p><form className="stack" onSubmit={async e=>{e.preventDefault();const {error}=await db.auth.signInWithPassword({email:form.email,password:form.password});setMsg(error?.message||"")}}><input type="email" placeholder="E-mail" onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Senha" onChange={e=>setForm({...form,password:e.target.value})} required/><button>Entrar</button></form><p>{msg}</p></div>;
if(!member)return <div className="card" style={{margin:60}}><h1>Acesso aguardando autorização</h1><p>{user.email}</p><p>Cadastre este usuário como membro no Supabase.</p><button onClick={()=>db.auth.signOut()}>Sair</button></div>;
return <><aside><h2>✦ Agency Hub</h2>{["Dashboard","Kanban","Clientes","Projetos","Financeiro"].map(t=><button className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{t}</button>)}<button onClick={()=>db.auth.signOut()}>Sair</button></aside><main><h1>{tab}</h1>{tab==="Dashboard"&&<div className="grid">{[["Clientes",clients.length],["Recebido",money(income)],["Custos",money(costs)],["Lucro líquido",money(income-costs)],["Sócio 1 — 50%",money((income-costs)/2)],["Sócio 2 — 50%",money((income-costs)/2)]].map(([k,v])=><div className="card" key={k}><p>{k}</p><h2>{v}</h2></div>)}</div>}
{tab==="Kanban"&&<div className="kanban">{stages.map(s=><div className="lane" key={s} onDragOver={e=>e.preventDefault()} onDrop={async e=>{const id=e.dataTransfer.getData("text");await db.from("clients").update({stage:s}).eq("id",id);load()}}><b>{s.toUpperCase()}</b>{clients.filter(c=>c.stage===s).map(c=><div draggable onDragStart={e=>e.dataTransfer.setData("text",c.id)} className="item" key={c.id}>{c.name}<p className="muted">{c.company}</p></div>)}</div>)}</div>}
{tab==="Clientes"&&<><div className="card"><h3>Novo cliente</h3><form className="form" onSubmit={e=>{e.preventDefault();add("clients",{name:form.name,company:form.company,email:form.email,phone:form.phone})}}>{["name","company","email","phone"].map(k=><input key={k} placeholder={k} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<button>Salvar cliente</button></form></div>{clients.map(c=><div className="item" key={c.id}>{c.name} — {c.company} — {c.email}</div>)}</>}
{tab==="Projetos"&&<><div className="card"><h3>Novo serviço</h3><form className="form" onSubmit={e=>{e.preventDefault();add("projects",{client_id:form.client_id,title:form.title,amount:Number(form.amount||0),due_date:form.due_date||null,recurring:!!form.recurring})}}><select onChange={e=>setForm({...form,client_id:e.target.value})}><option>Selecione cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input placeholder="Serviço" onChange={e=>setForm({...form,title:e.target.value})}/><input type="number" placeholder="Valor" onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" onChange={e=>setForm({...form,due_date:e.target.value})}/><label>Recorrente <input type="checkbox" onChange={e=>setForm({...form,recurring:e.target.checked})}/></label><button>Salvar serviço</button></form></div>{projects.map(p=><div className="item" key={p.id}>{p.title} — {money(Number(p.amount))}</div>)}</>}
{tab==="Financeiro"&&<><div className="card"><h3>Receitas e custos</h3><form className="form" onSubmit={e=>{e.preventDefault();add("transactions",{description:form.description,kind:form.kind,category:form.category||"geral",amount:Number(form.amount),paid_at:form.paid_at||null})}}><select onChange={e=>setForm({...form,kind:e.target.value})}><option>Tipo</option><option value="receita">Receita</option><option value="despesa">Despesa</option></select>{["description","category","amount"].map(k=><input key={k} placeholder={k} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<input type="date" onChange={e=>setForm({...form,paid_at:e.target.value})}/><button>Salvar lançamento</button></form></div>{tx.map(t=><div className="item" key={t.id}>{t.description} — {money(Number(t.amount))} — {t.kind}</div>)}</>}
<p>{msg}</p></main></>}
